"""add settlement fields to lessons

Revision ID: 001_add_settlement_fields
Revises:
Create Date: 2026-04-03

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_add_settlement_fields'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('teacher_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'teacher_amount')
    op.drop_column('lessons', 'settled_at')
    # ### end Alembic commands ###
