"""initial_schema

Revision ID: e87ee08f5642
Revises: 
Create Date: 2026-04-02 08:40:30.150419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e87ee08f5642'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=20)), server_default='{student}', nullable=False),
    sa.Column('active_role', sa.String(length=20), server_default='student', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('teacher_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='VND', nullable=False),
    sa.Column('teacher_type', sa.String(length=50), nullable=False),
    sa.Column('specialties', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('total_lessons', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=2, scale=1), server_default='0.0', nullable=False),
    sa.Column('total_reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('response_rate', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_teacher_profiles_avg_rating', 'teacher_profiles', [sa.literal_column('avg_rating DESC')], unique=False)
    op.create_index('idx_teacher_profiles_hourly_rate', 'teacher_profiles', ['hourly_rate'], unique=False)
    op.create_index('idx_teacher_profiles_teacher_type', 'teacher_profiles', ['teacher_type'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_availability_day_of_week_range'),
    sa.CheckConstraint('day_of_week IS NOT NULL OR specific_date IS NOT NULL', name='ck_availability_day_or_date'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending_confirmation', nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('platform_fee_rate', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lessons_scheduled_at', 'lessons', ['scheduled_at'], unique=False)
    op.create_index('idx_lessons_status', 'lessons', ['status'], unique=False)
    op.create_index('idx_lessons_student_id', 'lessons', ['student_id'], unique=False)
    op.create_index('idx_lessons_teacher_id', 'lessons', ['teacher_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), server_default='text', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('rating_overall', sa.SmallInteger(), nullable=False),
    sa.Column('rating_teaching', sa.SmallInteger(), nullable=True),
    sa.Column('rating_punctuality', sa.SmallInteger(), nullable=True),
    sa.Column('rating_communication', sa.SmallInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id')
    )
    op.create_index('idx_reviews_teacher_id', 'reviews', ['teacher_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index('idx_reviews_teacher_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('messages')
    op.drop_index('idx_lessons_teacher_id', table_name='lessons')
    op.drop_index('idx_lessons_student_id', table_name='lessons')
    op.drop_index('idx_lessons_status', table_name='lessons')
    op.drop_index('idx_lessons_scheduled_at', table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('availabilities')
    op.drop_table('wallets')
    op.drop_index('idx_teacher_profiles_teacher_type', table_name='teacher_profiles')
    op.drop_index('idx_teacher_profiles_hourly_rate', table_name='teacher_profiles')
    op.drop_index('idx_teacher_profiles_avg_rating', table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
